### ISSUE TITLE
StyleGAN FID on LSUN 256x256 was 2.65

### ISSUE THREAD

**Issue by chaman9000** [dorarad/gansformer#2]
The number was reported in Figure 10 of its paper:
https://arxiv.org/abs/1812.04948

**Comment by dorarad** [comment]
Hi there, yes there're gaps between numbers reported in StyleGAN papers and our work that stem from the length of training. As noted in the StyleGAN paper page 10 bottom they have trained their model for very long times: 25k image-steps for FFHQ, and 70k steps for Bedrooms. This is equivalent to 91 GPU-days of training on NVIDIA V100. 

Therefore, we compare all approaches given the same number of training steps: we explored training on different datasets in the ranges of 5k to 15k image-steps, about 5-7 shorter training than the experiments in the StyleGAN paper (about are equivalent to about 3-4 days on 4 GPUs). Under these settings, our model obtains better FID scores than StyleGAN as detailed in table 1 page 8 https://arxiv.org/pdf/2103.01209.pdf. See also footnote about that aspect in the bottom of page 8.

Furthermore, to give additional insight into the difference between models' performance over the course of training, you can see on page 9 figure 7 of our paper the learning curve in terms of FID score over steps, showing how given the same number of training steps the GANsformer performs better than StyleGAN both for the Bedroom dataset and especially for e.g. the CLEVR dataset. 
(Note also that the x-axis there is measured in training steps rather than image-steps but I'll fix it to match the more common image-step notation)

That's an important point so I hope my explanation here helps clarifying that!

**Comment by betterze** [comment]
@dorarad Have you try to train gansformer in Bedroom for longer time? Just to see if you it have btter FID than 2.65. Thank you for your help.

**Comment by dorarad** [comment]
Not yet because of compute budget reasons but I do hope actually to train one for longer in the next weeks. Will keep you updated!

**Comment by betterze** [comment]
@dorarad thx a lot.
