### ISSUE TITLE
Do we still need bidirectional interaction attention?

### ISSUE THREAD

**Issue by arieling** [dorarad/gansformer#24]
Hi Drew, Thank you a lot for sharing the code! 

I notice that all checkpoints you released don't have _**AttLayer_n2l.**_ So they are simplex + kmeans models?
I also notice that number reported in github has already a bit better than paper. Does it mean we can safely ignore bidirectional attention for now? Does it further help and boost cityscpaes FID better than 5.23?

**Comment by dorarad** [comment]
Hi, thanks for reaching out and apologies for the large delay in the response! 
The checkpoints indeed are of the simplex model and reach a bit better scores than the paper since kept training them further! I expect bidirectional attention to give further improvement but I still actively explore the architecture structure and ways to optimize it further so currently released pretrained models for the simplex version. Note that you can also train the duplex model using the --g-img2ltnt flag, hope it helps!
