### ISSUE TITLE
Metrics PR Error

### ISSUE THREAD

**Issue by bwhwang** [dorarad/gansformer#6]
Dear authors,

Thank you for your wonderful contribution!!!

When I tried to get precision and recall values during training by adding option, --metric pr, I got the following error

----------------------------------------------
\precision_recall.py", line 179, in _evaluate
    feats = self._gen_feats(Gs, inception, minibatch_size, num_gpus, Gs_kwargs)
NameError: name 'inception' is not defined
-----------------------------------------------

So, I have changed the  lines in precision_recall.py. After the modification, It seems to work.
I would greatly appreciate it if you kindly review my modification.

-------------------------------------------------------------------------
def _evaluate(self, Gs, Gs_kwargs, num_gpus, num_imgs, paths = None, **kwargs):

 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        if paths is not None: 
            # Extract features for local sample image files (paths)
----->  eval_features = self._paths_to_feats(paths, feat_func, minibatch_size, num_gpus, num_imgs)
        else:
            # Extract features for newly generated fake imgs
----->  eval_features = self._gen_feats(Gs, feature_net, minibatch_size, num_imgs, num_gpus, Gs_kwargs)

        # Compute precision and recall
        state = knn_precision_recall_features(ref_features = ref_features, eval_features = eval_features,
            feature_net = feature_net, nhood_sizes = [self.nhood_size], row_batch_size = self.row_batch_size,
----->  col_batch_size = self.row_batch_size, num_gpus = num_gpus, num_imgs = num_imgs)
        self._report_result(state.knn_precision[0], suffix = "_precision")
        self._report_result(state.knn_recall[0], suffix = "_recall")

-------------------------------------------------------------------------

**Comment by dorarad** [comment]
Sure! :) For the duplex originally yes but after I refactored all the code I had some training issue with the flag that I'm still exploring so for now I released only the simplex as the default and plan to follow up on that

**Comment by dorarad** [comment]
The differences between original simplex fro paper and improved simplex here:
* Using `--mapping_ltnt2ltnt` so that the latents communicate with each other directly through self-attention inside the mapping network before starting to generate the image.
* Adding the `--kmeans` from the duplex mode.
* Adding an additional global latent (`--style`) to the k standard latent components, such that first the one global latent modulates all the image features uniformly, and then the k latents modulate different regions based on the attention. The global latent is useful for coordinating global aspects of the image such as global lighting conditions, global style properties of e.g. a face, etc.
* Turns outs that with these changes no need to add the transformer to the discriminator, so for simplicity disabled that.

**Comment by dorarad** [comment]
Sure happy to help! :) I'll add these explanations also to the readme. I now also looked into your changes they're all almost correct (there was one more change needed in case `paths is not None` but it doesn't happen by default so won't affect the results you get). I made these changes to the repo: 
https://github.com/dorarad/gansformer/commit/175157caa8ec3547dc22a6ee6c10bc85f29e1958
